#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v20
# autospec commit: e180208
#
Name     : subversion
Version  : 1.14.3
Release  : 41
URL      : https://apache.osuosl.org/subversion/subversion-1.14.3.tar.gz
Source0  : https://apache.osuosl.org/subversion/subversion-1.14.3.tar.gz
Summary  : Subversion Delta Library
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause MIT
Requires: subversion-bin = %{version}-%{release}
Requires: subversion-lib = %{version}-%{release}
Requires: subversion-license = %{version}-%{release}
Requires: subversion-locales = %{version}-%{release}
Requires: subversion-man = %{version}-%{release}
Requires: subversion-perl = %{version}-%{release}
BuildRequires : apr-dev
BuildRequires : apr-util-dev
BuildRequires : buildreq-configure
BuildRequires : cyrus-sasl-dev
BuildRequires : dbus-dev
BuildRequires : doxygen
BuildRequires : expat-dev
BuildRequires : file-dev
BuildRequires : libsecret-dev
BuildRequires : pkgconfig(liblz4)
BuildRequires : pkgconfig(serf-1)
BuildRequires : pkgconfig(zlib)
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : ruby
BuildRequires : sed
BuildRequires : serf-dev
BuildRequires : sqlite-autoconf-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-test-skip-tests-that-are-not-python3-ready.patch

%description
Subversion, a version control system.
=====================================
$LastChangedDate: 2022-03-31 13:42:28 +0000 (Thu, 31 Mar 2022) $

%package bin
Summary: bin components for the subversion package.
Group: Binaries
Requires: subversion-license = %{version}-%{release}

%description bin
bin components for the subversion package.


%package dev
Summary: dev components for the subversion package.
Group: Development
Requires: subversion-lib = %{version}-%{release}
Requires: subversion-bin = %{version}-%{release}
Provides: subversion-devel = %{version}-%{release}
Requires: subversion = %{version}-%{release}
Requires: cyrus-sasl-dev
Requires: file-dev
Requires: lz4-dev

%description dev
dev components for the subversion package.


%package lib
Summary: lib components for the subversion package.
Group: Libraries
Requires: subversion-license = %{version}-%{release}

%description lib
lib components for the subversion package.


%package license
Summary: license components for the subversion package.
Group: Default

%description license
license components for the subversion package.


%package locales
Summary: locales components for the subversion package.
Group: Default

%description locales
locales components for the subversion package.


%package man
Summary: man components for the subversion package.
Group: Default

%description man
man components for the subversion package.


%package perl
Summary: perl components for the subversion package.
Group: Default
Requires: subversion = %{version}-%{release}

%description perl
perl components for the subversion package.


%prep
%setup -q -n subversion-1.14.3
cd %{_builddir}/subversion-1.14.3
%patch -P 1 -p1
pushd ..
cp -a subversion-1.14.3 buildavx2
popd

%build
## build_prepend content
export CPPFLAGS=-P
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1730249101
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --with-utf8proc=internal \
--without-swig \
--with-serf \
--with-gnome-keyring
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
## build_prepend content
export CPPFLAGS=-P
## build_prepend end
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --with-utf8proc=internal \
--without-swig \
--with-serf \
--with-gnome-keyring
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check PARALLEL=1 || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1730249101
rm -rf %{buildroot}
## install_prepend content
make swig-pl DESTDIR=%{buildroot}
## install_prepend end
mkdir -p %{buildroot}/usr/share/package-licenses/subversion
cp %{_builddir}/subversion-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/subversion/2001ec12a76fab136661bf0850b354ce06312809 || :
cp %{_builddir}/subversion-%{version}/subversion/libsvn_subr/lz4/LICENSE %{buildroot}/usr/share/package-licenses/subversion/10bf56381baaf07f0647b93a810eb4e7e9545e8d || :
cp %{_builddir}/subversion-%{version}/subversion/libsvn_subr/utf8proc/LICENSE.md %{buildroot}/usr/share/package-licenses/subversion/1383cee8b844e0df97aea12a3ea98912af5081dd || :
cp %{_builddir}/subversion-%{version}/tools/dev/svnmover/linenoise/LICENSE %{buildroot}/usr/share/package-licenses/subversion/3bd655bcdbe6f4f14e9da385f1953c50dd89ea8e || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
%find_lang subversion
## install_append content
make install-swig-pl DESTDIR=%{buildroot} LIBRARY_PATH=%{buildroot}/usr/lib64 INSTALLDIRS=vendor

# Clean up unwanted files.  These are usually handled as part of install step,
# before we are able to install the bindings above.
rm -f %{buildroot}/usr/lib/perl5/*/*/perllocal.pod
rm -f %{buildroot}/usr/lib64/*.la
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/svn
/V3/usr/bin/svnadmin
/V3/usr/bin/svnbench
/V3/usr/bin/svndumpfilter
/V3/usr/bin/svnfsfs
/V3/usr/bin/svnlook
/V3/usr/bin/svnmucc
/V3/usr/bin/svnrdump
/V3/usr/bin/svnserve
/V3/usr/bin/svnsync
/V3/usr/bin/svnversion
/usr/bin/svn
/usr/bin/svnadmin
/usr/bin/svnbench
/usr/bin/svndumpfilter
/usr/bin/svnfsfs
/usr/bin/svnlook
/usr/bin/svnmucc
/usr/bin/svnrdump
/usr/bin/svnserve
/usr/bin/svnsync
/usr/bin/svnversion

%files dev
%defattr(-,root,root,-)
/usr/include/subversion-1/mod_authz_svn.h
/usr/include/subversion-1/mod_dav_svn.h
/usr/include/subversion-1/svn-revision.txt
/usr/include/subversion-1/svn_auth.h
/usr/include/subversion-1/svn_base64.h
/usr/include/subversion-1/svn_cache_config.h
/usr/include/subversion-1/svn_checksum.h
/usr/include/subversion-1/svn_client.h
/usr/include/subversion-1/svn_cmdline.h
/usr/include/subversion-1/svn_compat.h
/usr/include/subversion-1/svn_config.h
/usr/include/subversion-1/svn_ctype.h
/usr/include/subversion-1/svn_dav.h
/usr/include/subversion-1/svn_delta.h
/usr/include/subversion-1/svn_diff.h
/usr/include/subversion-1/svn_dirent_uri.h
/usr/include/subversion-1/svn_dso.h
/usr/include/subversion-1/svn_error.h
/usr/include/subversion-1/svn_error_codes.h
/usr/include/subversion-1/svn_fs.h
/usr/include/subversion-1/svn_hash.h
/usr/include/subversion-1/svn_io.h
/usr/include/subversion-1/svn_iter.h
/usr/include/subversion-1/svn_md5.h
/usr/include/subversion-1/svn_mergeinfo.h
/usr/include/subversion-1/svn_nls.h
/usr/include/subversion-1/svn_opt.h
/usr/include/subversion-1/svn_opt_impl.h
/usr/include/subversion-1/svn_path.h
/usr/include/subversion-1/svn_pools.h
/usr/include/subversion-1/svn_props.h
/usr/include/subversion-1/svn_quoprint.h
/usr/include/subversion-1/svn_ra.h
/usr/include/subversion-1/svn_ra_svn.h
/usr/include/subversion-1/svn_repos.h
/usr/include/subversion-1/svn_sorts.h
/usr/include/subversion-1/svn_string.h
/usr/include/subversion-1/svn_subst.h
/usr/include/subversion-1/svn_time.h
/usr/include/subversion-1/svn_types.h
/usr/include/subversion-1/svn_types_impl.h
/usr/include/subversion-1/svn_user.h
/usr/include/subversion-1/svn_utf.h
/usr/include/subversion-1/svn_version.h
/usr/include/subversion-1/svn_wc.h
/usr/include/subversion-1/svn_x509.h
/usr/include/subversion-1/svn_xml.h
/usr/lib64/libsvn_auth_gnome_keyring-1.so
/usr/lib64/libsvn_client-1.so
/usr/lib64/libsvn_delta-1.so
/usr/lib64/libsvn_diff-1.so
/usr/lib64/libsvn_fs-1.so
/usr/lib64/libsvn_fs_fs-1.so
/usr/lib64/libsvn_fs_util-1.so
/usr/lib64/libsvn_fs_x-1.so
/usr/lib64/libsvn_ra-1.so
/usr/lib64/libsvn_ra_local-1.so
/usr/lib64/libsvn_ra_serf-1.so
/usr/lib64/libsvn_ra_svn-1.so
/usr/lib64/libsvn_repos-1.so
/usr/lib64/libsvn_subr-1.so
/usr/lib64/libsvn_swig_perl-1.so
/usr/lib64/libsvn_wc-1.so
/usr/lib64/pkgconfig/libsvn_auth_gnome_keyring.pc
/usr/lib64/pkgconfig/libsvn_client.pc
/usr/lib64/pkgconfig/libsvn_delta.pc
/usr/lib64/pkgconfig/libsvn_diff.pc
/usr/lib64/pkgconfig/libsvn_fs.pc
/usr/lib64/pkgconfig/libsvn_fs_fs.pc
/usr/lib64/pkgconfig/libsvn_fs_util.pc
/usr/lib64/pkgconfig/libsvn_fs_x.pc
/usr/lib64/pkgconfig/libsvn_ra.pc
/usr/lib64/pkgconfig/libsvn_ra_local.pc
/usr/lib64/pkgconfig/libsvn_ra_serf.pc
/usr/lib64/pkgconfig/libsvn_ra_svn.pc
/usr/lib64/pkgconfig/libsvn_repos.pc
/usr/lib64/pkgconfig/libsvn_subr.pc
/usr/lib64/pkgconfig/libsvn_wc.pc
/usr/share/man/man3/SVN::Base.3
/usr/share/man/man3/SVN::Client.3
/usr/share/man/man3/SVN::Core.3
/usr/share/man/man3/SVN::Delta.3
/usr/share/man/man3/SVN::Fs.3
/usr/share/man/man3/SVN::Ra.3
/usr/share/man/man3/SVN::Repos.3
/usr/share/man/man3/SVN::Wc.3

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libsvn_auth_gnome_keyring-1.so.0.0.0
/V3/usr/lib64/libsvn_client-1.so.0.0.0
/V3/usr/lib64/libsvn_delta-1.so.0.0.0
/V3/usr/lib64/libsvn_diff-1.so.0.0.0
/V3/usr/lib64/libsvn_fs-1.so.0.0.0
/V3/usr/lib64/libsvn_fs_fs-1.so.0.0.0
/V3/usr/lib64/libsvn_fs_util-1.so.0.0.0
/V3/usr/lib64/libsvn_fs_x-1.so.0.0.0
/V3/usr/lib64/libsvn_ra-1.so.0.0.0
/V3/usr/lib64/libsvn_ra_local-1.so.0.0.0
/V3/usr/lib64/libsvn_ra_serf-1.so.0.0.0
/V3/usr/lib64/libsvn_ra_svn-1.so.0.0.0
/V3/usr/lib64/libsvn_repos-1.so.0.0.0
/V3/usr/lib64/libsvn_subr-1.so.0.0.0
/V3/usr/lib64/libsvn_wc-1.so.0.0.0
/usr/lib64/libsvn_auth_gnome_keyring-1.so.0
/usr/lib64/libsvn_auth_gnome_keyring-1.so.0.0.0
/usr/lib64/libsvn_client-1.so.0
/usr/lib64/libsvn_client-1.so.0.0.0
/usr/lib64/libsvn_delta-1.so.0
/usr/lib64/libsvn_delta-1.so.0.0.0
/usr/lib64/libsvn_diff-1.so.0
/usr/lib64/libsvn_diff-1.so.0.0.0
/usr/lib64/libsvn_fs-1.so.0
/usr/lib64/libsvn_fs-1.so.0.0.0
/usr/lib64/libsvn_fs_fs-1.so.0
/usr/lib64/libsvn_fs_fs-1.so.0.0.0
/usr/lib64/libsvn_fs_util-1.so.0
/usr/lib64/libsvn_fs_util-1.so.0.0.0
/usr/lib64/libsvn_fs_x-1.so.0
/usr/lib64/libsvn_fs_x-1.so.0.0.0
/usr/lib64/libsvn_ra-1.so.0
/usr/lib64/libsvn_ra-1.so.0.0.0
/usr/lib64/libsvn_ra_local-1.so.0
/usr/lib64/libsvn_ra_local-1.so.0.0.0
/usr/lib64/libsvn_ra_serf-1.so.0
/usr/lib64/libsvn_ra_serf-1.so.0.0.0
/usr/lib64/libsvn_ra_svn-1.so.0
/usr/lib64/libsvn_ra_svn-1.so.0.0.0
/usr/lib64/libsvn_repos-1.so.0
/usr/lib64/libsvn_repos-1.so.0.0.0
/usr/lib64/libsvn_subr-1.so.0
/usr/lib64/libsvn_subr-1.so.0.0.0
/usr/lib64/libsvn_swig_perl-1.so.0
/usr/lib64/libsvn_swig_perl-1.so.0.0.0
/usr/lib64/libsvn_wc-1.so.0
/usr/lib64/libsvn_wc-1.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/subversion/10bf56381baaf07f0647b93a810eb4e7e9545e8d
/usr/share/package-licenses/subversion/1383cee8b844e0df97aea12a3ea98912af5081dd
/usr/share/package-licenses/subversion/2001ec12a76fab136661bf0850b354ce06312809
/usr/share/package-licenses/subversion/3bd655bcdbe6f4f14e9da385f1953c50dd89ea8e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/svn.1
/usr/share/man/man1/svnadmin.1
/usr/share/man/man1/svndumpfilter.1
/usr/share/man/man1/svnlook.1
/usr/share/man/man1/svnmucc.1
/usr/share/man/man1/svnrdump.1
/usr/share/man/man1/svnsync.1
/usr/share/man/man1/svnversion.1
/usr/share/man/man5/svnserve.conf.5
/usr/share/man/man8/svnserve.8

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*

%files locales -f subversion.lang
%defattr(-,root,root,-)

